### ISSUE TITLE
Sending, ideas

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/BossBarTest#1]
Not showing up when joining
not showing up when moving > 32 Blocks away
no real despawn on level change
no timer yet
Create second plugin for displaying diferent messages every x seconds

**Comment by SerezhaIvanov** [comment]
Make infinity block not 32 and make color for bar.

**Comment by inxomnyaa** [comment]
Coloring the text may work tomorrow
Coloring the bar doesn't work in PE (sadly.)

**Comment by TheAppleGamer** [comment]
@thebigsmileXD There is a lot of code here for a boss bar, I've got one with a few less features but works just fine

**Comment by inxomnyaa** [comment]
Colored text now functional, wither invisible

**Comment by inxomnyaa** [comment]
@TheAppleGamer i want to make mine so you can just build code on it. Even the biggest noob should know how to use it lol :D _me_

**Comment by HarryMyStick** [comment]
public function onEnable() {
        $this->getLogger()->info("Plugins Make By Harry");
		switch($event->getBlock(Water instanceof Lava){
			case "1":
			$this->setInteractBlock(DIAMOND_OAR, 0, 1);
			case "2"
            $this->setInteractBlock(REDSTONE_OAR, 0, 1);
            case "3":
            $this->setInteractBlock(STONE, 0, 1);
            }else{
            $this->setInteractBlock(COBBLESTONE, 0, 1);
		 break;
			}
		}
	  public function onDisable() {
		  $this->getLogger()->info("Plugins Dừng lại");
	  }
}
help me!!!. I want this plugins works for active lava with water to form different blocks
please help me

**Comment by inxomnyaa** [comment]
Outdated issue - Flagged as fixed
