### ISSUE TITLE
Not work with Genisys

### ISSUE THREAD

**Issue by NycuR0** [thebigsmileXD/BossBarTest#2]
Not work with Genisys ,spam with this error:

Warning: Missing argument 2 for xenialdan\BossBarAPI\API::playerMove(), called in phar:///root/teste/plugins/phar_BossAnnouncement-master_PzVBVs9k2Zf64yg.phar/src/xenialdan/BossAnnouncement/Main.php on line 56 and defined in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 149

Notice: Undefined variable: eid in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 154

Warning: Missing argument 2 for xenialdan\BossBarAPI\API::playerMove(), called in phar:///root/teste/plugins/phar_BossAnnouncement-master_PzVBVs9k2Zf64yg.phar/src/xenialdan/BossAnnouncement/Main.php on line 56 and defined in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 149

Notice: Undefined variable: eid in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 154

Warning: Missing argument 2 for xenialdan\BossBarAPI\API::playerMove(), called in phar:///root/teste/plugins/phar_BossAnnouncement-master_PzVBVs9k2Zf64yg.phar/src/xenialdan/BossAnnouncement/Main.php on line 56 and defined in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 149

Notice: Undefined variable: eid in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 154

Warning: Missing argument 2 for xenialdan\BossBarAPI\API::playerMove(), called in phar:///root/teste/plugins/phar_BossAnnouncement-master_PzVBVs9k2Zf64yg.phar/src/xenialdan/BossAnnouncement/Main.php on line 56 and defined in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 149

Notice: Undefined variable: eid in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 154

Warning: Missing argument 2 for xenialdan\BossBarAPI\API::playerMove(), called in phar:///root/teste/plugins/phar_BossAnnouncement-master_PzVBVs9k2Zf64yg.phar/src/xenialdan/BossAnnouncement/Main.php on line 56 and defined in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 149

Notice: Undefined variable: eid in phar:///root/teste/plugins/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API.php on line 154
[19:18:49] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'BossAnnouncement v1.0.0': Undefined class constant 'DATA_FLAG_NOAI' on xenialdan\BossAnnouncement\Main
[19:18:49] [Server thread/CRITICAL]: Error: "Undefined class constant 'DATA_FLAG_NOAI'" (EXCEPTION) in "/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API" at line 36
[19:18:49] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'BossBarTest v1.0.0': Undefined class constant 'DATA_FLAG_NOAI' on xenialdan\BossBarTest\Main
[19:18:49] [Server thread/CRITICAL]: Error: "Undefined class constant 'DATA_FLAG_NOAI'" (EXCEPTION) in "/phar_BossBarAPI-master (1)_MWE1IzJ2Hc5BkK6.phar/src/xenialdan/BossBarAPI/API" at line 36

**Comment by inxomnyaa** [comment]
Haahahahahahhaaha
