### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by VCraftMCPE** [thebigsmileXD/BossBarTest#3]
Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'BossBarTest v1.0.0': Undefined class constant 'DATA_FLAG_NOAI' on xenialdan\BossBarTest\Main

**Comment by VCraftMCPE** [comment]
Also BossAnnouncement won't work

**Comment by inxomnyaa** [comment]
What about the bossannouncement?

**Comment by inxomnyaa** [comment]
First bug fixed
