### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by GamingGapple** [thebigsmileXD/BossBarTest#4]
Error: "Undefined class constant 'DATA_LEAD_HOLDER_EID'" (EXCEPTION) in "/BossBarAPI.phar/src/xenialdan/BossBarAPI/API" at line 36
08.12 00:55:06 [Server] | Elywing thread:CRITICAL  "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'BossBarTest v1.0.0': Undefined class constant 'DATA_LEAD_HOLDER_EID' on xenialdan\BossBarTest\Main

**Comment by inxomnyaa** [comment]
Elwing is missing that data xD
what a shame

**Comment by ApexDevelops** [comment]
It works if you change it to DATA_LEAD_HOLDER

**Comment by inxomnyaa** [comment]
It was changed on 0.16, Elwing is just outdated

**Comment by ApexDevelops** [comment]
See
![img_0844](https://cloud.githubusercontent.com/assets/23283168/21047131/064f2680-bdbd-11e6-9953-320ab576c12d.PNG)

**Comment by inxomnyaa** [comment]
Following the PMMP aka official PocketMine, DATA_LEAD_HOLDER_EID is correct. Elwing has to modify this
